### ISSUE TITLE
Amplify console stuck at 'Your build is being queued. If your build has not started in over a minute, click the button below.'

### ISSUE THREAD

**Issue by abhi6689-develop** [aws-amplify/amplify-console#1197]
** Please describe which feature you have a question about? **
Having an issue with the Amplify Deploy feature. 

** Provide additional details**

I was trying to deploy a webapp using Amplify(using a github repository). Got no errors in the process but the status is stuck at "Your build is being queued. If your build has not started in over a minute, click the button below."

**Comment by Athena96** [comment]
Hi @abhi6689-develop can you please share your appId. Also, how many Amplify apps do you have in your account? Thanks!

**Comment by abhi6689-develop** [comment]
The appId is: d2kn574eeb7h1y, I have one amplify app in my account. Thanks!

**Comment by Athena96** [comment]
Hi, yes it looks like your build was queued, but never actually started. And it appears you have not re-tried the build yet, can you retry by opening your app in Amplify Console, then clicking on the branch name, then clicking the "Redeploy this version" button. Please let us know if you continue to face this issue.

**Comment by abhi6689-develop** [comment]
Hey, tried doing that, but clicking on the branch name leads to a blank screen.

**Comment by DivonC** [comment]
I'm having this same issue. Any word on how to fix this?

**Comment by Cheederah** [comment]
Please has this been resolved? As i'm currently experiencing the same issue

**Comment by jackfreeman279** [comment]
I also have this same issue when deploying a fresh CRA instance **d3syxt6d8mx8lh** following the tutorial video, only using Bitbucket instead of Github. When clicking through to the branch, master, it gives me a blank screen; looks like there's a 403 error within amplify's main.js

**Comment by abhi6689-develop** [comment]
@Cheederah @jackfreeman279 it ended up being a permissions issue for me, but the way aws works, never received an error which said I didn't have the necessary permissions, the thing just wouldn't work. Ask your administrator for full amplify access(the suggested json file on aws docs doesn't give you all of them). Cheers!

**Comment by jackfreeman279** [comment]
Checked and re-checked my Amplify permissions and they are all in order, but I still experience the same issue.

What's peculiar is that the successfully built application and a correct screenshot of it is present in the "All Apps" dashboard, but when going into the app from there I still get this issue.

**Comment by Athena96** [comment]
@abhi6689-develop are you still facing this issue?

**Comment by abhi6689-develop** [comment]
@Athena96 no, it has been resolved, was an issue with my permissions.

**Comment by Athena96** [comment]
Great, thanks! Resolving

**Comment by oj-m** [comment]
@Athena96 Which permission worked for you?  `AdministratorAccess-Amplify` still fails for me with no errors, no warnings, no logs, nothing.

**Comment by VincentGaoHJ** [comment]
Same issue here, I add all the policies including  `AdministratorAccess-Amplify`, still can see nothing from the console but the website seems to work well.

> @Athena96 Which permission worked for you? `AdministratorAccess-Amplify` policy is on the account and it still fails for me with no errors, no warnings, no logs, nothing.

**Comment by caseyplummer4haliontech** [comment]
> Same issue here, I add all the policies including `AdministratorAccess-Amplify`, still can see nothing from the console but the website seems to work well.
> 
> > @Athena96 Which permission worked for you? `AdministratorAccess-Amplify` policy is on the account and it still fails for me with no errors, no warnings, no logs, nothing.

Try initiating the job via the command console and you'll likely get more detail to see the problem. See my notes above.

**Comment by amartyadav** [comment]
It was a permissions issue for me too. Turns out that the `AdministratorAccess-Amplify` is not enough. I had to give my IAM user (the one that I was using to deploy) full administrator access from the IAM management using my 'Administrator' IAM user. It worked then.

**Comment by nitinkaushik1910** [comment]
The issue is solved for me by adding permission for amplify. Make sure all the Amplify actions mentioned in the URL - https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsamplify.html 

is provided to IAM policy. It will solve the issue both from console and command for building the Amplify app.

**Comment by WarrenK-design** [comment]
This policy below should do the trick, read more on the policy's as @nitinkaushik1910 suggested [here](url).

If you read the ```AdministratorAccess-Amplify ``` it does not give you access to all Amplify actions, the ```SID``` for it is also marked as ```CLISDKCalls```, I don't think it was intended for console use, new policy maybe should be added for this? 

```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "UpdatedAmplifyAdminAccess",
            "Effect": "Allow",
            "Action": [
                "amplify:CreateApp",
                "amplify:CreateBackendEnvironment",
                "amplify:GetApp",
                "amplify:CreateDeployment",
                "amplify:CreateDomainAssociation",
                "amplify:CreateWebHook",
                "amplify:GetBackendEnvironment",
                "amplify:ListApps",
                "amplify:ListBackendEnvironments",
                "amplify:CreateBranch",
                "amplify:GetBranch",
                "amplify:GenerateAccessLogs",
                "amplify:GetArtifactUrl",
                "amplify:GetBackendEnvironment",
                "amplify:GetDomainAssociation",
                "amplify:GetJob",
                "amplify:GetWebHook",
                "amplify:UpdateApp",
                "amplify:ListArtifacts",
                "amplify:ListBranches",
                "amplify:ListDomainAssociations",
                "amplify:ListJobs",
                "amplify:ListTagsForResource",
                "amplify:ListWebHooks",
                "amplify:DeleteBranch",
                "amplify:DeleteApp",
                "amplify:DeleteBackendEnvironment",
                "amplify:DeleteDomainAssociation",
                "amplify:DeleteJob",
                "amplify:DeleteWebHook",
                "amplify:StartDeployment",
                "amplify:StartJob",
                "amplify:StopJob",
                "amplify:TagResource",
                "amplify:UntagResource",
                "amplify:UpdateApp",
                "amplify:UpdateBranch",
                "amplify:UpdateDomainAssociation",
                "amplify:UpdateWebHook",
                "amplifybackend:*"
            ],
            "Resource": "*"
        }
    ]
}
```
