### ISSUE TITLE
Unable to delete both of my Amplify apps

### ISSUE THREAD

**Issue by vguhesan** [aws-amplify/amplify-console#1281]
**Describe the bug**
In the AWS Amplify console, I have two apps - [SimplePillMinder_www, SimplePillMinder_web]. I would like to delete them both so that I can recreate them using CloudFront due to SSL provisioning issues. But I'm unable to delete them. Console says "Deleting ..." as a growl notification but even after a few hours, the apps remain.

**To Reproduce**
1. Go to AWS Amplify console under my account.
2. Click on each of the App [SimplePillMinder_www, SimplePillMinder_web] and then from the Actions drop-down (upper-right), choose "Delete App".
3. Confirm by typing "delete" on the confirm-prompt.
4. Wait for a while and app does not get deleted.

**Expected behavior**
App should be deleted and the deployed web server should not be running. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser FireFox
 - Version 83.0 (64-bit)

**Comment by akilisosa** [comment]
I have had the same problem. I created like 6-7 dummy projects.

**Comment by ganipcanot** [comment]
Are either of you still having this issue?  If so could you please share your appId and region where this is happening?

**Comment by akilisosa** [comment]
arn:aws:amplify:us-east-1:************:apps/d19msw6n9ca06c  - this one is a practice with the elastic search geo location search feature which i have had problems with.  I don't know if this is the info you need, or if something else. I deleted the stacks, and elastic search ec2 instance, and when i click on the app, it says backend successfully deleted, but it still shows up on my screen. 

Some of them say backend update successful, last updated, normal stuff. 

My error occured a couple of days ago initially i was working with the elastic search custom resolvers, i was getting a bunch of random errors from that, and then i tried to just recreate the project and start over because i was getting an unknown error, and kept getting all of these unknown server errors, so i would try to delete, and restart and I was just having the hardest time.

**Comment by vguhesan** [comment]
The issue was intermittent. It is now resolved. Closing issue. Thank you.

**Comment by ganipcanot** [comment]
There was a large scale event (LSE) that was affecting multiple services sometime last week in **us-east-1 (IAD)** so this may have just been an intermittent issue.  If anyone is still experiencing issues please feel free to re-open this ticket or open a new one.

**Comment by akilisosa** [comment]
![image](https://user-images.githubusercontent.com/18223349/100677557-3af1a700-3339-11eb-8df7-125b3826a27d.png)


That is cool, but i still have all these random projects in my project folder that I am unable to delete. When i select delete, it goes through the motions and i get a little blue box at the top, that says it is deleteing things but nothing happens

**Comment by akilisosa** [comment]
ok it works now... 👍

**Comment by descaloni-cc** [comment]
Im having this issue in us-east-1 and us-west-2
I have about 4 test apps I cannot delete
