### ISSUE TITLE
Can't delete test app: `Removing backend envs for app XXX failed`

### ISSUE THREAD

**Issue by pedroapfilho** [aws-amplify/amplify-console#1330]
**Describe the bug**
Can't delete test app from the dashboard

![Screenshot 2020-12-03 at 15 07 11](https://user-images.githubusercontent.com/13142568/101030503-a033db00-3579-11eb-828c-4fd495350494.png)
![Screenshot 2020-12-03 at 15 07 51](https://user-images.githubusercontent.com/13142568/101030536-a2963500-3579-11eb-8cba-c80e887027eb.png)
![Screenshot 2020-12-03 at 15 09 18](https://user-images.githubusercontent.com/13142568/101030547-a3c76200-3579-11eb-8ce1-af3e2e693909.png)
![Screenshot 2020-12-03 at 15 09 26](https://user-images.githubusercontent.com/13142568/101030550-a3c76200-3579-11eb-8d3b-443bc3bbd8dc.png)
![Screenshot 2020-12-03 at 15 09 46](https://user-images.githubusercontent.com/13142568/101030555-a45ff880-3579-11eb-8440-0d3e6f3cee52.png)

**Comment by dunethomas** [comment]
I'm having this exact same problem... I've tried everything and I can't delete an app

**Comment by jrmccoy64** [comment]
I too am having the same problem.

**Comment by swaminator** [comment]
@jrmccoy64 @dunethomas @pedroapfilho we'll look into this asap and post an update.

**Comment by arrivabeni** [comment]
Same error here.

**Comment by geeodee** [comment]
Hi I am having the same issue error here

**Comment by shrhawk-entertainer** [comment]
same issue

**Comment by ideaplan** [comment]
same issue i am facing right now

**Comment by jrmccoy64** [comment]
As a follow up, I discovered my problem is that I tried to delete via the Amplify console, though I had originally created via the cli. In an attempt to clean up manually, I deleted an associated S3 bucket. Now, I’m unable to delete via cli as it fails due to bucket not found. There does not appear to be a way to manually clean things up. My backend is shown as deleted, but the app doesn’t delete, as any attempts start with trying to delete the backend, failing with bucket not found.

**Comment by ahkai86** [comment]
same issues unable to remove amplify app after setup as test app

**Comment by kirtap7** [comment]
Using the AWS CLI command for Amplify [delete-backend-environment](https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-backend-environment.html) might help.

**Comment by jrmccoy64** [comment]
Hi, in my case the backend is already deleted and trying to use the cli produces an error because of a missing s3 bucket, which I deleted in an attempt to manually clean up.

**Comment by arrivabeni** [comment]
I was able to delete after run the command proposed by @kirtap7 .

> Using the AWS CLI command for Amplify [delete-backend-environment](https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-backend-environment.html) might help.
> sample command `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`

If you got stuck at the same point as me, you won't be able to see the app-id in the AWS console, to find it just try to delete app again and it will be exposed in the error message. After run the delete-backend command go back again to the console and delete the app.

**Comment by jrmccoy64** [comment]
Awesome! I was able to get it to work too.
Thank you for your support.

**Comment by ahkai86** [comment]
yes and many thanks to @kirtap7 ! was able to delete it using the cli command  =)

**Comment by pedroapfilho** [comment]
Confirmed, after deleting the environment with: 

```
aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>
```

I can go to the `Amplify Console` and delete the app there.

Thanks @kirtap7 !

@swaminator I think this gives you a clue about what's going on, and how to fix it. I'll keep this issue opened until you guys fix it.

**Comment by cbettridgehs** [comment]
Im experiencing the same issue. When running the aws cli delete command suggested above I get:

"An error occurred (NotFoundException) when calling the DeleteBackendEnvironment operation: App d2ncju1xmfjiad not found". 

The app id and environment name I am using are correct. Region is eu-west-1. When I first encountered this issue I manually deleted the underlying resources including the cloud formation template. I've tried deleting the app and environment through the console, AWS cli and Amplify cli but nothing is working.

**Comment by GanizaniSitara** [comment]
Thanks @kirtap7, your suggestion worked here as well.  @swaminator still an issue as of today

**Comment by Basovs** [comment]
> I was able to delete after run the command proposed by @kirtap7 .
> 
> > Using the AWS CLI command for Amplify [delete-backend-environment](https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-backend-environment.html) might help.
> > sample command `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`
> 
> If you got stuck at the same point as me, you won't be able to see the app-id in the AWS console, to find it just try to delete app again and it will be exposed in the error message. After run the delete-backend command go back again to the console and delete the app.
> 
> Thank you!

Hacker! - Thnks! :)

**Comment by swaminator** [comment]
We've fixed all the issues with deleting environments. If you still have stacks stuck in deleting please let us know.

**Comment by Harshith-Shetty** [comment]
I tried this 👇 method it worked for me.

1.  first go to [Cloud​Formation](https://aws.amazon.com/cloudformation/)  service and delete the stack that is associated with your amplify app. First delete the nested stack if there and then the root stack
2. Then you install Amazon [CLI](https://docs.amplify.aws/cli) if not, to your local device
3. Then open Command Prompt and type the following Commands
4. `amplify pull`
5. you would be asked for your profile and all those steps and then asked for the amplify app to select, then go with all the option suitable with that amplify app 
6. type the command `amplify delete` and the further agree to delete by typing `y`
7. your amplify app would be deleted wait for a min to refresh the data in the console.

**Comment by fluidpixel** [comment]
This issues is not resolved. I'm seeing it as of today. Even if I delete the whole Amplify App, once the app is restored, the env still thinks it already exists. I have manually deleted various buckets and stacks, and it seems the lack of a stack/bucket is causing an issue here.

**Comment by fluidpixel** [comment]
deleting the backend thorough the cli as above cleared them out from the interface

**Comment by tangytang** [comment]
the latest command that worked for me was: 
aws amplify delete-app --app-id <YOUR_APP_ID>

Cheers.

**Comment by HSin-Tse** [comment]
same issue

**Comment by SourceCode** [comment]
> same issue
> 
> 1. make a clean dir.  &&. cd into the-clean-fir
> 2. $ amplify pull --appId d2n0k04wudqwef --envName dev
> 3. select region  file
> 4. aws amplify delete-backend-environment --app-id d2n0k04wudqwef --environment-name dev
> 5. delete again use console
> 
> its work for me

I have had to use this call to remove some environments that were beyond broken as well.  I had already deleted some resources or stacks in cloudformation which would cause this break (failure to delete).  Using the AWS CLI allowed me to finally remove them.

**Comment by rezab777** [comment]
If you need to get a list of your apps and want to get their ids use
`aws amplify list-apps
`or
`aws amplify list-apps >> apps.json
`to get it as a json file

**Comment by victor-rami** [comment]
I ran into this issue also when accidentally closing vscode during  `amplify init` was running. My local amplify cli didnt recognize the credentials (using SSO) and i was receiving an error.

Running this in the AWS console as the IAM user you created for your app solved the issue.

**Comment by Al-Spheres** [comment]
> Using the AWS CLI command for Amplify [delete-backend-environment](https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-backend-environment.html) might help. sample command `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`

I had the same issue and this worked for me!

**Comment by kknd4eva** [comment]
I ran into this issue when doing the following

1. Creating a backend for an existing frontend via the console. 
2. The backend creation failed due to hitting the S3 bucket limit. 
3. The delete via the console continued to fail with Removing backend envs for app XXX failed
4. I tried deleting the Cloudformation stack first, then repeating #3 - same error. 
5. Running the command via the CLI was the only way to resolve this issue (See @Al-Spheres above).

**Comment by chrisl777** [comment]
Note that I had to add the `--profile` argument, as in: `aws amplify delete-backend-environment --app-id <APP_ID> --environment-name <ENV_NAME> --profile <PROFILE_NAME>`

**Comment by fti-sfuke** [comment]
**[Solution For : Can't delete test app: Removing backend envs for app XXX failed](url)**

**When some resources have been deleted manually (S3 & Cloudformation) then**

`$amplify delete ` 
Gives Following :

```
Unable to remove env: dev because deployment bucket amplify-amplifyAPPName-dev-XYZ-deployment does not exist or has been deleted.
  
Stack has already been deleted or does not exist
```
Please look at this:

```
C:user\samadhan\Amplify-Projects\amplifyapp-demo>amplify delete

? Are you sure you want to continue? This CANNOT be undone. (This will delete all the environments of the project from the cloud and wi
pe out all the local files created by Amplify CLI) Yes
- Deleting resources from the cloud. This may take a few minutes...
Deleting env: dev.
Unable to remove env: dev because deployment bucket amplify- 
amplifyinitdemo-dev-131139-deployment does not exist or has been deleted.

Stack has already been deleted or does not exist

\ Deleting resources from the cloud. This may take a few minutes...App 
 dfwx13s2bgtb1 not found.

App dfwx13s2bgtb1 not found.
√ Project already deleted in the cloud.
Project deleted locally.
App Amplify App still showing in Console Unable to delete from Console. Please Take a look : Amplify App Console Unable to Delete App Error

```
**Solution: Using AWS CLI You Can be Fixed This Issue. 
Step 1 ) Make Sure AWS CLI is configured with the Same AWS Account if Not Please Create IAM User & Configure it with the same Region.**

```
C:user\samadhan\Amplify-Projects\amplifyapp-demo>aws configure
AWS Access Key ID [****************HZHF]: ****************ICHK
AWS Secret Access Key [****************iBJl]:****************SnaX
Default region name [ap-south-1]: ap-south-1
Default output format [json]: json

```
**Step 2 ) Use Following AWS CLI Commands.**

```
C:user\samadhan\Amplify-Projects\amplifyapp-demo>>aws amplify help
Available Commands
******************
* create-app
* create-backend-environment
* create-deployment
* delete-app
* delete-backend-environment
* get-app
* list-apps
* list-backend-environments

C:user\samadhan\Amplify-Projects\amplifyapp-demo>aws amplify list-apps
{
    "apps": [
        {
        "appId": "d39pvb2qln4v7l",
        "appArn": "arn:aws:amplify:ap-south-1:850915XXXXX:apps/d39pvb2qln4v7l",
        "name": "react-amplify-demo-project",
            "tags": {},
            "platform": "WEB",
            "createTime": 1640206703.371,
            "updateTime": 1640206703.371,
            "environmentVariables": {
                "_LIVE_PACKAGE_UPDATES": "[{\"pkg\":\"@aws-amplify/cli\",\"type\":\"npm\",\"version\":\"latest\"}]"
            },
        {
            "appId": "d2jsl78ex1asqy",
            "appArn": "arn:aws:amplify:ap-south-1:85091xxxxxxxx:apps/d2jsl78ex1asqy",
            "name": "fullstackapp",
            "tags": {},
            "platform": "WEB",
            "createTime": 1640250148.974,
            "updateTime": 1640250148.974,
            "environmentVariables": {
                "_LIVE_PACKAGE_UPDATES": "[{\"pkg\":\"@aws-amplify/cli\",\"type\":\"npm\",\"version\":\"latest\"}]"
            }
        }
```
**
**Step 3) Use Following CLI Command to Delete App Or App Env**

```
C:user\samadhan\Amplify-Projects\amplifyapp-demo>aws amplify delete-app --app-id d39pvb2qln4v7l
{
    "app": {
        "appId": "d39pvb2qln4v7l",
        "appArn": "arn:aws:amplify:ap-south-1:8509xxxxx:apps/d39pvb2qln4v7l",
        "name": "react-amplify-demo-project",
        "repository": "https://gitlab.com/samadhanfuke/react-amplify-demo-project",
        "platform": "WEB",
        "createTime": 1639077857.194,
        "updateTime": 1639077857.194,
        "iamServiceRoleArn": "arn:aws:iam::850915xxxx:role/amplifyconsole-backend-role",
        "environmentVariables": {
            "_LIVE_UPDATES": "[{\"name\":\"Amplify CLI\",\"pkg\":\"@aws-amplify/cli\",\"type\":\"npm\",\"version\":\"latest\"}]"
        },
        "defaultDomain": "d39pvb2qln4v7l.amplifyapp.com",
        "enableBranchAutoBuild": false,
        "enableBranchAutoDeletion": false,
        "enableBasicAuth": false,
        "customRules": [
            {
                "source": "/<*>",
                "target": "/index.html",
                "status": "404-200"
            }
        ],
        "productionBranch": {
            "lastDeployTime": 1639078272.607,
            "status": "SUCCEED",
            "branchName": "preview"
        },
        "buildSpec": "version: 1\nbackend:\n  phases:\n    # IMPORTANT - Please verify your build commands\n    build:\n      commands:\n        - '# Execute Amplify CLI with the helper script'\n        - amplifyPush --simple\nfrontend:\n  phases:\n    build:\n      commands: []\n  artifacts:\n    # IMPORTANT - Please verify your build output directory\n    baseDirectory: /\n    files:\n      - '**/*'\n  cache:\n    paths: []\n",
        "customHeaders": "",
        "enableAutoBranchCreation": false
    }
}
```
**Amplify App With Environment Successfully Deleted. Check-in Amplify Console.**

**Comment by samadhanfuke** [comment]
**[Solution For : Can't delete test app: Removing backend envs for app XXX failed](url)**

**When some resources have been deleted manually (S3 & Cloudformation) then**

`$amplify delete ` 
Gives Following :

```
Unable to remove env: dev because deployment bucket amplify-amplifyAPPName-dev-XYZ-deployment does not exist or has been deleted.
  
Stack has already been deleted or does not exist
```
Please look at this:

```
C:user\samadhan\Amplify-Projects\amplifyapp-demo>amplify delete

? Are you sure you want to continue? This CANNOT be undone. (This will delete all the environments of the project from the cloud and wi
pe out all the local files created by Amplify CLI) Yes
- Deleting resources from the cloud. This may take a few minutes...
Deleting env: dev.
Unable to remove env: dev because deployment bucket amplify- 
amplifyinitdemo-dev-131139-deployment does not exist or has been deleted.

Stack has already been deleted or does not exist

\ Deleting resources from the cloud. This may take a few minutes...App 
 dfwx13s2bgtb1 not found.

App dfwx13s2bgtb1 not found.
√ Project already deleted in the cloud.
Project deleted locally.
App Amplify App still showing in Console Unable to delete from Console. Please Take a look : Amplify App Console Unable to Delete App Error

```
**Solution: Using AWS CLI You Can be Fixed This Issue. 
Step 1 ) Make Sure AWS CLI is configured with the Same AWS Account if Not Please Create IAM User & Configure it with the same Region.**

```
C:user\samadhan\Amplify-Projects\amplifyapp-demo>aws configure
AWS Access Key ID [****************HZHF]: ****************ICHK
AWS Secret Access Key [****************iBJl]:****************SnaX
Default region name [ap-south-1]: ap-south-1
Default output format [json]: json

```
**Step 2 ) Use Following AWS CLI Commands.**

```
C:user\samadhan\Amplify-Projects\amplifyapp-demo>>aws amplify help
Available Commands
******************
* create-app
* create-backend-environment
* create-deployment
* delete-app
* delete-backend-environment
* get-app
* list-apps
* list-backend-environments

C:user\samadhan\Amplify-Projects\amplifyapp-demo>aws amplify list-apps
{
    "apps": [
        {
        "appId": "d39pvb2qln4v7l",
        "appArn": "arn:aws:amplify:ap-south-1:850915XXXXX:apps/d39pvb2qln4v7l",
        "name": "react-amplify-demo-project",
            "tags": {},
            "platform": "WEB",
            "createTime": 1640206703.371,
            "updateTime": 1640206703.371,
            "environmentVariables": {
                "_LIVE_PACKAGE_UPDATES": "[{\"pkg\":\"@aws-amplify/cli\",\"type\":\"npm\",\"version\":\"latest\"}]"
            },
        {
            "appId": "d2jsl78ex1asqy",
            "appArn": "arn:aws:amplify:ap-south-1:85091xxxxxxxx:apps/d2jsl78ex1asqy",
            "name": "fullstackapp",
            "tags": {},
            "platform": "WEB",
            "createTime": 1640250148.974,
            "updateTime": 1640250148.974,
            "environmentVariables": {
                "_LIVE_PACKAGE_UPDATES": "[{\"pkg\":\"@aws-amplify/cli\",\"type\":\"npm\",\"version\":\"latest\"}]"
            }
        }
```
**
**Step 3) Use Following CLI Command to Delete App Or App Env**

```
C:user\samadhan\Amplify-Projects\amplifyapp-demo>aws amplify delete-app --app-id d39pvb2qln4v7l
{
    "app": {
        "appId": "d39pvb2qln4v7l",
        "appArn": "arn:aws:amplify:ap-south-1:8509xxxxx:apps/d39pvb2qln4v7l",
        "name": "react-amplify-demo-project",
        "repository": "https://gitlab.com/samadhanfuke/react-amplify-demo-project",
        "platform": "WEB",
        "createTime": 1639077857.194,
        "updateTime": 1639077857.194,
        "iamServiceRoleArn": "arn:aws:iam::850915xxxx:role/amplifyconsole-backend-role",
        "environmentVariables": {
            "_LIVE_UPDATES": "[{\"name\":\"Amplify CLI\",\"pkg\":\"@aws-amplify/cli\",\"type\":\"npm\",\"version\":\"latest\"}]"
        },
        "defaultDomain": "d39pvb2qln4v7l.amplifyapp.com",
        "enableBranchAutoBuild": false,
        "enableBranchAutoDeletion": false,
        "enableBasicAuth": false,
        "customRules": [
            {
                "source": "/<*>",
                "target": "/index.html",
                "status": "404-200"
            }
        ],
        "productionBranch": {
            "lastDeployTime": 1639078272.607,
            "status": "SUCCEED",
            "branchName": "preview"
        },
        "buildSpec": "version: 1\nbackend:\n  phases:\n    # IMPORTANT - Please verify your build commands\n    build:\n      commands:\n        - '# Execute Amplify CLI with the helper script'\n        - amplifyPush --simple\nfrontend:\n  phases:\n    build:\n      commands: []\n  artifacts:\n    # IMPORTANT - Please verify your build output directory\n    baseDirectory: /\n    files:\n      - '**/*'\n  cache:\n    paths: []\n",
        "customHeaders": "",
        "enableAutoBranchCreation": false
    }
}
```
**Amplify App With Environment Successfully Deleted. Check-in Amplify Console.**

**Comment by SGrebenkin** [comment]
> Using the AWS CLI command for Amplify [delete-backend-environment](https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-backend-environment.html) might help. sample command `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`

That worked, thanks dude

**Comment by mikedorsey1021** [comment]
> Note that I had to add the `--profile` argument, as in: `aws amplify delete-backend-environment --app-id <APP_ID> --environment-name <ENV_NAME> --profile <PROFILE_NAME>`

adding the `--profile <PROFILE_NAME>` worked. thank you
