### ISSUE TITLE
Creating backend on Amplify Console fails.

### ISSUE THREAD

**Issue by hi120ki** [aws-amplify/amplify-console#138]
I set amplify latest version on Amplify Console.

Yesterday 2019/9/19, released amplify-cli 3.8.0, fails to creating backend on Amplify Console.
and today 2019/9/20, released amplify-cli 3.9.0, fails same situation.
(2019/9/18 amplify-cli 3.7.0, succeed to deploy)

Running "amplify push" in local has no problem. (every amplify-cli version)

My Amplify Console log is here

```
# Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-09-19T04:06:33.181Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-09-19T04:06:33.189Z [INFO]: # Start initializing Amplify environment: env
2019-09-19T04:06:33.194Z [INFO]: STACKINFO=context.print.fancy is not a function
                                 TypeError: context.print.fancy is not a function
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:53:35
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:33:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:14:53)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:8:71
                                 at new Promise (<anonymous>)
                                 at __awaiter (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:4:12)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:41:38)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:64:56
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:33:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:14:53)
                                 # Importing Amplify environment: env (amplify env import)
2019-09-19T04:06:34.137Z [INFO]: Scanning for plugins...
2019-09-19T04:06:41.925Z [INFO]: Plugin scan successful
2019-09-19T04:06:41.939Z [INFO]: You must pass in the configs of the environment in an object format using the --config flag
2019-09-19T04:06:41.984Z [ERROR]: !!! Build failed
2019-09-19T04:06:42.076Z [ERROR]: !!! Non-Zero Exit Code detected
2019-09-19T04:06:42.076Z [INFO]: # Starting environment caching...
2019-09-19T04:06:42.077Z [INFO]: # Uploading environment cache artifact...
2019-09-19T04:06:42.178Z [INFO]: # Environment caching completed
Terminating logging...
```

and my amplify.yml is

```yml
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
  customHeaders:
    - pattern: '**/*'
      headers:
      - key: 'X-Frame-Options'
        value: 'deny'
      - key: 'X-XSS-Protection'
        value: '1; mode=block'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
```

Maybe I did't commit critical change on my project.

I'm waiting for your great support. Thank you.

**Comment by JoshuaTruscott** [comment]
I'm also currently having this issue using CLI version 3.9.0
amplify push is successful but the deployment fails.

**Comment by garyleefight** [comment]
> I'm also currently having this issue using CLI version 3.9.0
> amplify push is successful but the deployment fails.

The deployment issue should be fixed. Could you have a try?

**Comment by mrducky4** [comment]
It still fails for me, using Amplify CLI 3.9.0. The Amplify console build page looks different than a couple days ago. I can't find any way to download the logs today. I copied this log fragment:
```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-09-24T23:58:34.057Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-09-24T23:58:34.064Z [INFO]: # Start initializing Amplify environment: test
2019-09-24T23:58:34.065Z [INFO]: STACKINFO=context.print.fancy is not a function
                                 TypeError: context.print.fancy is not a function
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:53:35
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:33:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:14:53)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:8:71
                                 at new Promise (<anonymous>)
                                 at __awaiter (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:4:12)
                                 at Object.run (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env/get.js:41:38)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:67:56
                                 at step (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:33:23)
                                 at Object.next (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/lib/commands/env.js:14:53)
                                 # Importing Amplify environment: test (amplify env import)
```

**Comment by garyleefight** [comment]
@mrducky4 The STACK_INFO is messed up due to CLI bug. Anyone who meets this error can reset the stackInfo with the following setting
```yaml
backend:
  phases:
    build:
      commands:
        - envCache --set stackInfo ""
        - amplifyPush --simple
```
Make sure after the envCache is reset, you remove the `envCache --set stackInfo ""` line

**Comment by mrducky4** [comment]
Thanks @garyleefight , but I don't understand. Where and when exactly would I make such a change? I don't have any such thing in my project. I do see a similar thing in the Amplify Console build settings page, in a section showing amplify.yml. It has this:
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
```

**Comment by garyleefight** [comment]
@mrducky4 Click 'Build settings' on left navigation bar. Then click edit for 'App build specification'. Insert 
- envCache --set stackInfo "" before 
- amplifyPush --simple

Then redeploy your app. Hope it works for you. Thanks！

**Comment by mrducky4** [comment]
@garyleefight now it is failing even earlier, cloning the repo, with "Permission denied (publickey)" error. I can't tell if the problem is on AWS side or bitbucket side. After that is resolved, I can try again on this STACKINFO issue.

**Comment by garyleefight** [comment]
@mrducky4 Sorry about it. We have a Bitbucket issue right now. 
Please track on this issue: https://github.com/aws-amplify/amplify-console/issues/157

**Comment by mrducky4** [comment]
after using the bitbucket reauthenticate workaround, and the - envCache --set stackInfo "" workaround, I was able to deploy with amplify console. I had to use the envCache workaround for each environment (branch) I was deploying.
