### ISSUE TITLE
Build fails with "Starting SSR Build..."

### ISSUE THREAD

**Issue by tjto** [aws-amplify/amplify-console#1824]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3srkgpabkig16

### Region

eu-central-1

### Amplify Console feature

Build settings

### Describe the bug

Starting from 11 May 2021, with no changes in our code or build configuration, all of our builds have started failing with
```
Starting SSR Build...
AccessDenied
```

### Expected behavior

Build should be successful since no change 

### Reproduction steps

Just re-run the pipeline

### Build Settings

```yaml
BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - yarn install
            build:
              commands:
                - next build && next export
          artifacts:
            baseDirectory: out
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
```

**Comment by nimacks** [comment]
@tjto we identified an issue in how we detect your SSR app and have resolved the issue. Can you retry your build and let us know if  you are unblocked?

**Comment by tjto** [comment]
@nimacks At the moment I am blocking by https://github.com/aws-amplify/amplify-console/issues/1825 so cannot verify yet

**Comment by jericopulvera** [comment]
This also happens to our build number 352

We got the same error
```
Starting SSR Build...
AccessDenied
```

and then on the following builds, the error is the exact same as #1825.

We're also using Next.js and I don't know if that's relevant as the problem is in the Cloning the Repository stage.

**Comment by nimacks** [comment]
We've deployed a fix for this issue. Can you try again and let us know when you're unblocked?

**Comment by ssousa33** [comment]
> We've deployed a fix for this issue. Can you try again and let us know when you're unblocked?

I'm experiencing the same problem - should I redeploy and see what happens, or is there another intermediary step that I should take? 

Thanks

**Comment by tjto** [comment]
It is fixed. Thanks

**Comment by tjto** [comment]
@ssousa33 After re-run the pipeline the second time, it is back to failed with same error.
Other app has same symptom as well

**Comment by ssousa33** [comment]
> @ssousa33 After re-run the pipeline the second time, it is back to failed with same error.
> Other app has same symptom as well

my app is live again -  there is a new cloudfront redirect in the "Rewrites & Redirects" dialog in the amplify gui console. had to play with the existing rewrites but it seems okay for now

**Comment by nimacks** [comment]
@tjto is this resolved now?

**Comment by tjto** [comment]
@nimacks It is not resolved. Try with 4.50.0 as @ssousa33  suggested but no luck.

**Comment by ssousa33** [comment]
@nimacks, same here, now.  all build steps pass until :

`2021-05-13T14:23:23.093Z [INFO]: Export successful. Files written to /codebuild/output/src806663020/src/tuned-next/out
2021-05-13T14:23:23.099Z [INFO]: Done in 94.23s.
2021-05-13T14:23:23.103Z [INFO]: Starting SSR Build...
2021-05-13T14:26:10.028Z [INFO]: Error
Terminating logging...`

**Comment by heikkikurkela** [comment]
@nimacks build and deploy succeed now but deployed app gives an "redirected too many times" error.

**Rewrites and redirects rule**
/<*> | /index.html | 404 (Redirect)

Amplify **Deploy** log
```
2021-05-13T20:08:48 [INFO]: Beginning deployment for application xxxxxxxx, branch:<branch>, buildId 0000000XYZ
2021-05-13T20:08:48 [INFO]: SSR Deployment complete
```
App is not accessible

**Comment by Athena96** [comment]
@heikkikurkela can you please share your appId

**Comment by Athena96** [comment]
@tjto @heikkikurkela there was an issue with our detection of Next.js apps. The issue has been resolved, and I manually restored your app framework to what it was before. Please try another build and let us know if you continue to face this issue. thanks!

**Comment by tjto** [comment]
Seems to work now.

**Comment by heikkikurkela** [comment]
@Athena96 could you give us a brief explanation of what and why such a problem occurred? You have introduced a new detection feature or something? Everything worked fine until May 11th and then the builds suddenly broke down. Something has had to change.

Appreciate your reply and thanks in advance!
