### ISSUE TITLE
Recently pushed commit is not reflected in the latest automated build

### ISSUE THREAD

**Issue by jericopulvera** [aws-amplify/amplify-console#1847]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dptgqyo1az3e7

### Region

ap-southeast-1

### Amplify Console feature

Not applicable

### Describe the bug

I made some visible changes to our project and pushed it into our bitbucket repo's main branch.

The AWS Amplify Console triggers a new build but the cloned repo is not the latest one.

### Expected behavior

The latest pushed commit should be reflected in the latest build.

### Reproduction steps

1. git add .
2. git commit -m "commit message"
3. git push

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build:$AWS_BRANCH
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
  customHeaders:
     - pattern: '**/*.json'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.js'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.css'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.gif'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.ico'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.jpg'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.png'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.svg'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.mp4'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.webm'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*'
       headers:
        - key: 'Strict-Transport-Security'
          value: 'max-age=31536000; includeSubDomains'
        - key: 'X-Frame-Options'
          value: 'SAMEORIGIN'
        - key: 'X-XSS-Protection'
          value: '1; mode=block'
        - key: 'X-Content-Type-Options'
          value: 'nosniff'
```

### Additional information

Connecting a new branch that came from the main branch build is also outdated.

I suspect that the automated build keeps cloning a specific commit from the past.

**Comment by jericopulvera** [comment]
This issue might be the cause of the applied fix for issue #1825 #1824.

We're using Next.js SSG.

**Comment by Athena96** [comment]
@jericopulvera sorry you are facing this issue. It looks like you ran a build during a period where we had an issue with SSG detection. I have manually reset your status to SSG, so your issue should be resolved. Please feel free to re-open if you continue to face this issue.

**Comment by jericopulvera** [comment]
> @jericopulvera sorry you are facing this issue. It looks like you ran a build during a period where we had an issue with SSG detection. I have manually reset your status to SSG, so your issue should be resolved. Please feel free to re-open if you continue to face this issue.

Latest build still does not reflect the latest commit.

**Comment by jericopulvera** [comment]
I created a new hidden page and I see that it is generated on the build phase but it's still not appearing in the connected domain.

Could this be a caching issue on your side?

**Comment by jericopulvera** [comment]
@Athena96 I cannot re-open the issue.

**Comment by ssousa33** [comment]
@Athena96 I am experienceing the same issue, and was previously experiencing the issues cited in #1824. I was able to yesterday, but the latest commit was not reflected, and upon pushing a new commit today, the build failed at :

`2021-05-18T15:58:13.052Z [INFO]: Export successful. Files written to /codebuild/output/src253453846/src/tuned-next/out
2021-05-18T15:58:13.058Z [INFO]: Done in 94.97s.
2021-05-18T15:58:13.062Z [INFO]: Starting SSR Build...
2021-05-18T16:01:04.085Z [INFO]: Error
Terminating logging...`

**Comment by Athena96** [comment]
@ssousa33 can you share your appId, thanks

**Comment by jericopulvera** [comment]
@Athena96 I was able to create a new amplify app with Next.js - SSR detected as the framework and I got no issues so far. The old app has Web as the detected framework.

I'm currently using the old app to redirect my main domain to the www subdomain in the new app. 
I hope that the issue with the old app "dptgqyo1az3e7" gets fixed.

Hope this info helps you.

**Comment by ssousa33** [comment]
> @ssousa33 can you share your appId, thanks

@Athena96 - app id is d1monpkxtxrpp5

**Comment by ACPK** [comment]
@Athena96 - I'm having the same error for two Amplify apps (staging and production). One has the framework as blank while the other has SSR. They should both be SSG.

**Comment by leighkendell** [comment]
I'm also experiencing the same build issue with no error

appid: dvz5hlwhv3cxu
region: ap-southeast-2

```
2021-05-21T07:27:37.529Z [INFO]: Starting SSR Build...
2021-05-21T07:29:25.492Z [INFO]: Error
```

**Comment by Athena96** [comment]
@leighkendell I'm seeing this build error
`ModuleNotFoundError: Module not found: Error: Can't resolve 'mongodb' in '/codebuild/output/src069219851/src/livestock-pricing-fe/node_modules/typeorm/platform'`

**Comment by leighkendell** [comment]
> @leighkendell I'm seeing this build error
> `ModuleNotFoundError: Module not found: Error: Can't resolve 'mongodb' in '/codebuild/output/src069219851/src/livestock-pricing-fe/node_modules/typeorm/platform'`

Weird... That looks to be a peer dependency as I am not using typeorm  or mongodb explicitly. I don't have this issue building in other environments like bitbucket pipelines and vercel. Is it possible to have these errors actually exposed to the amplify console? Otherwise I'll be troubleshooting this blind 😬

**Comment by jericopulvera** [comment]
> @Athena96 I was able to create a new amplify app with Next.js - SSR detected as the framework and I got no issues so far. The old app has Web as the detected framework.
> 
> I'm currently using the old app to redirect my main domain to the www subdomain in the new app.
> I hope that the issue with the old app "dptgqyo1az3e7" gets fixed.
> 
> Hope this info helps you.

@Athena96 

We ran into this issue again in the new amplify app (d15izgm8c268bd) instance we've created.

I can see in the amplify build log that the new page is generated but it's not reflected on the site.

The old app (dptgqyo1az3e7) also still has this issue.

**Comment by jericopulvera** [comment]
This might be related to #604

**Comment by Athena96** [comment]
closing this issue, feel free to re-open if you continue to face it. thanks!

**Comment by GeorgiStavrev** [comment]
I'm running into the same issue. My app id is `d2ohstmzpe02tu`
