### ISSUE TITLE
Uable to deploy the amplify app

### ISSUE THREAD

**Issue by abinayakumaran** [aws-amplify/amplify-console#1952]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-2

### Amplify Console feature

Manual deploys

### Describe the bug

My amplify is  successfully build  but deployment is failed but its works previous. I just change my production branch in amplify app settings. How i get the detailed logs for this failure without using cloud trail.

### Expected behavior

How i resolve the deploy issue or how i get detailed logs.

### Reproduction steps

1. Trigger by push code to the specific branch.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by asungomez** [comment]
I'm getting this issue too. The logs display no errors, but the deployment fails.

App ID: `ddylx7eexyjhq`
Region: `us-east-2`

**Comment by slavaman** [comment]
Getting issue too:
Region: eu-central-1
App ID: d97nogqzdty16

**Comment by dein0s** [comment]
Getting stuck at provision step
App ID: `d67fy3h9m237g`
Region: `us-east-1`

**Comment by luke3butler** [comment]
Provision step never finishes for me either.
App ID: `d3qxsxgi0uq2oc`  
Region: `us-east-1`

Nothing is the logs looks wrong. Just seems to freeze somewhere between provision finishing and build starting.

**Comment by luiskcs89** [comment]
Same for me
App ID: d1pynf4s98mcr3
Region: us-east-1

**Comment by nlaffey-icario** [comment]
Also stuck at provision step.
App ID: d37ut799xx808t
Region: us-east-1

**Comment by nimacks** [comment]
We are currently experiencing increasing build latency rates for the AWS Amplify Console in the US-EAST-1 region

**Comment by luiskcs89** [comment]
Now it seems to be failing in the build of the front end. With no changes from previous versions that were working.
App ID: d1pynf4s98mcr3
Region: us-east-1

**Comment by nimacks** [comment]
This issue has been resolved.

**Comment by asungomez** [comment]
I'm still experiencing this issue.

**Comment by slavaman** [comment]
I am still experiencing the issue
Region: eu-central-1
App ID: d376lnejsqekw1
