### ISSUE TITLE
Build started failing with Unable to clone github repository error

### ISSUE THREAD

**Issue by pooja8bhatt** [aws-amplify/amplify-console#357]
**App id**:arn:aws:amplify:us-east-1:261481771863:apps/d3lnafpf6f1oy3
**Region**:us-east-1

**Issue/question**
Our build has started failing since yesterday(10th Jan 2020) with `Permission Denied` error when cloning the git repository. Everything was working before that. We have not made any changes to our settings in Github. We have admin rights in Github. Tried to reauthenticate app many times already but that didn't help. 

**Error message**
![image](https://user-images.githubusercontent.com/6544173/72198217-4782bd80-3450-11ea-914e-1a080b95f7d4.png)
![image](https://user-images.githubusercontent.com/6544173/72198219-510c2580-3450-11ea-935d-fe30570d5f97.png)

**Comment by cslogan-red** [comment]
Hi @pooja8bhatt , this can happen if the SSH deploy key that the Console creates when you initially connect your repo accidentally gets deleted from the Github repo (Github repo > Settings > Deploy keys) You can reset this with the "Re-authenticate app" button in General Settings, however for Github repos it also requires you first delete the webhook that the Console creates to listen for repo activity **before** you re-authenticate.

1. Github repo > Settings > Webhooks, and delete the webhook created by the Console (it will look similar to: guid.execute-api.us-east-1.amazonaws.com/prod/github (push))
2. Once the webhook is deleted, then you can click the "Re-authenticate app" button in General Settings in the Console, and it will re-establish a new SSH deploy key as well as a new webhook, at that point your builds will continue working.

**Comment by pooja8bhatt** [comment]
HI @cslogan-red, thank you for solving the mystery for us. As you mentioned deploy keys were missing. But we didn't know that for reauthenticating a github repo we need to delete webhooks! Will delete the webhooks and reauthenticate. Thanks again 😌

**Comment by tslater** [comment]
@cslogan-red I am having a hard time finding the "re-authenticate app" button in general settings...


![Uploading image.png…]()

**Comment by tslater** [comment]
@cslogan-red I am having a hard time finding the "re-authenticate app" button in general settings...


![image](https://user-images.githubusercontent.com/449326/95487852-13dab280-0952-11eb-9670-2512bfa4879c.png)

**Comment by specter01wj** [comment]
"re-authenticate app" becomes "Reconnect repository"

**Comment by clovus** [comment]
This is still an issue and the steps above are not working for many users (https://github.com/aws-amplify/amplify-console/issues/727), including me. 

Please reopen this!

**Comment by lebull** [comment]
I'm this behavior as well after setting up a second amplify project pointing to the same repository.  Removing the webhooks and reconnecting the repository does not fix the issue.

Is this worth another issue?

```
2020-12-09T18:53:04.654Z [INFO]: Git SSH Key acquired
2020-12-09T18:53:04.725Z [INFO]: # Cloning repository: git@github.com:lebull/PhasmophobiaQuickGrid.git
2020-12-09T18:53:04.801Z [INFO]: Agent pid 121
2020-12-09T18:53:04.806Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2020-12-09T18:53:05.128Z [INFO]: Cloning into 'PhasmophobiaQuickGrid'...
2020-12-09T18:53:05.474Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
2020-12-09T18:53:06.140Z [INFO]: # Checking for Git submodules at: /codebuild/output/src015065065/src/PhasmophobiaQuickGrid/.gitmodules
2020-12-09T18:53:06.169Z [INFO]: # Retrieving cache...
2020-12-09T18:53:06.211Z [INFO]: # Extracting cache...
2020-12-09T18:53:06.219Z [INFO]: # Extraction completed
2020-12-09T18:53:06.220Z [INFO]: # Retrieving environment cache...
2020-12-09T18:53:06.268Z [INFO]: # Retrieved environment cache
2020-12-09T18:53:20.053Z [ERROR]: !!! Error: ENOENT: no such file or directory, scandir '/codebuild/output/src015065065/src/PhasmophobiaQuickGrid/emffive'
2020-12-09T18:53:20.262Z [INFO]: # Starting environment caching...
2020-12-09T18:53:20.262Z [INFO]: # Environment caching completed
Terminating logging...
2020-12-09T18:53:04.654Z [INFO]: Git SSH Key acquired
2020-12-09T18:53:04.725Z [INFO]: # Cloning repository: git@github.com:lebull/PhasmophobiaQuickGrid.git
2020-12-09T18:53:04.801Z [INFO]: Agent pid 121
2020-12-09T18:53:04.806Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2020-12-09T18:53:05.128Z [INFO]: Cloning into 'PhasmophobiaQuickGrid'...
2020-12-09T18:53:05.474Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
2020-12-09T18:53:06.140Z [INFO]: # Checking for Git submodules at: /codebuild/output/src015065065/src/PhasmophobiaQuickGrid/.gitmodules
2020-12-09T18:53:06.169Z [INFO]: # Retrieving cache...
2020-12-09T18:53:06.211Z [INFO]: # Extracting cache...
2020-12-09T18:53:06.219Z [INFO]: # Extraction completed
2020-12-09T18:53:06.220Z [INFO]: # Retrieving environment cache...
2020-12-09T18:53:06.268Z [INFO]: # Retrieved environment cache
2020-12-09T18:53:20.053Z [ERROR]: !!! Error: ENOENT: no such file or directory, scandir '/codebuild/output/src015065065/src/PhasmophobiaQuickGrid/emffive'
2020-12-09T18:53:20.262Z [INFO]: # Starting environment caching...
2020-12-09T18:53:20.262Z [INFO]: # Environment caching completed

```

**Comment by JakeVz** [comment]
https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html

This solution worked for me -- I needed to create and add a Service Role

**Comment by lebull** [comment]
Tbe issue for me was resolved by not using amplify-cli version 4.38.x.

**Comment by HarborneD** [comment]
This is an issue for me and I'm following the tutorial of how to deploy an amplify solution - I don't think this is fixed?
