### ISSUE TITLE
Manual deployment doesn't connect to backend

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-console#596]
**Issue/question**
I deployed 2 different project's manually. (Not using git repo).
Both are built with react & uses only congito auth & graphql backed by dynamodb.
And its not syncing with GraphQL API. I am using datastore so its handling CRUD operation offline.
The Auth is working. I am able to log in and do everything except sync.
Both work properly in devlopment version locally.
But not working in production version in custom domain or with amplify domain.

### I cannot sync with graphql API.

I don't know what I am doing wrong. 
- `npm run build`  
- zip all files in build folder
- deploy manually 

```
import Amplify from '@aws-amplify/core'
import config from './aws-exports'

Amplify.configure(config)
```
This is added to index.tsx

The auth is working just graphql API is not syncing.

**Error message**
There is no error or warning of any kind.

**Comment by adriencg** [comment]
@apoorvmote Mind referencing any docs/guides you followed?

**Comment by swaminator** [comment]
@apoorvmote do you have the aws-exports.js file as part of your build output?

**Comment by apoorvmote** [comment]
@adriencg  [https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html](https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html) 
This is the guide that I followed.

@swaminator I didn't change anything from default settings. I built app with 
- `create react app` 
- `amplify init`
- `amplify add api`
- `amplify push`
- `npm run build`
I didn't touch default webpack settings or react settings. **The cognito auth is working**. I am able to log in. 
Aren't all settings saved together??

**Comment by apoorvmote** [comment]
Today I tried 2nd method.
- First tested if it can sync in deveopment mode on localhost
- `amplify add hosting`
- `Hosting with Amplify Console`
- `Manual deployment`

Again it syncs on development mode but doesn't sync in production mode.

### The email based cognito auth is working. Only graphql sync is not working.

**Comment by apoorvmote** [comment]
I am using typescript with react. So I tested by createing `config.ts` and copied everything from `aws-exports.js` 
Same result. It doesn't sync.
 
I manually copied everything from `aws-exports.js` to `index.tsx`
Same result. It doesn't sync.

I checked the build folder and in `build/static/js/mainxxxxchunk.js.map` has actual graphql endpoint.
Still it doesn't sync in production but syncs in development.

**Comment by swaminator** [comment]
Just to better understand,  you have two backend envs `dev` and `prod`? Things work in `dev` but not in `prod`?

**Comment by apoorvmote** [comment]
no React development env vs React production env. On localhost it runs on react development environment and it syncs but on custom domain or amplify app domain its in react production environment where it doesn't sync.

**Comment by apoorvmote** [comment]
even in latest [amplify blog post](https://aws.amazon.com/blogs/mobile/amplify-framework-announces-new-rearchitected-ui-component-and-modular-javascript-libraries/) they are using `aws-amplify` vs `@aws-amplify/core` So to add config I tried both ways. 

Again in both ways it syncs on react development build on localhost. Doesn't sync on react production build on custom domain or amplify app domain.

**Comment by apoorvmote** [comment]
Aparantly its solved in https://github.com/aws-amplify/amplify-js/issues/5448

But I can't verify until next stable release. Still I am closing this issue. Will open again if it fails.

**Comment by cnegrisanu** [comment]
@apoorvmote 
I still have the same issue. I spent the entire last week trying to troubleshoot. Works fine on localhost and syncs to the backend env no matter which one I choose, but when deployed to amplify hosting... there's no attempt to connect to the backend api to sync records.
