### ISSUE TITLE
Errors in amplify.yaml are incorrectly reported as a connection error to your app

### ISSUE THREAD

**Issue by cjsedwards** [aws-amplify/amplify-console#727]
If there is a YAML syntax error in amplify.yaml, you get the following:

```There was an issue connecting to your repo provider, click "Re-authenticate app" in General Settings, and then try your build again.```

This is misleading, and let me down 30 minutes of debugging my connection to github before I realized this error had nothing to do with what the actual problem was.

**Comment by kahdojay** [comment]
@cjsedwards thanks for reporting. Can you share your appid and region so we can take a closer look?

**Comment by cjsedwards** [comment]
https://us-west-2.console.aws.amazon.com/amplify/home?region=us-west-2#/d2bp2r8zohs9b/master/236

**Comment by cjsedwards** [comment]
FYI - I've resolved my underlying issue, but the incorrect error message is still a bug IMO

**Comment by Joycehao19** [comment]
Hi @cjsedwards, where did you get this message? in build stage?

**Comment by cjsedwards** [comment]
Yes
![image](https://user-images.githubusercontent.com/6901289/83434538-ed32cb00-a3f7-11ea-8994-46a90436c5fa.png)

**Comment by Joycehao19** [comment]
Would you mind tell me which syntax error do you have? I tried to add something on my amplify.yaml, but I didn't get the same error message

**Comment by cjsedwards** [comment]
Here is the syntax I had in my file:
```
      commands:
        - 'VUE_APP_WEB_PUSH_PUBLIC_KEY=$WEB_PUSH_PUBLIC_KEY' >>> .env
        - 'VUE_APP_WEB_PUSH_PUBLIC_KEY=$WEB_PUSH_PUBLIC_KEY' >> .env
        - yarn run build	        - yarn run build
```

**Comment by cjsedwards** [comment]
```
2020-06-01T15:35:33.969Z [ERROR]: !!! YAMLException: bad indentation of a sequence entry at line 15, column 62:
                                  ... UBLIC_KEY=$WEB_PUSH_PUBLIC_KEY' >> .env
```

**Comment by Joycehao19** [comment]
I reproduced the issue. Added it to team backlog. Thank you for reporting the issue!

**Comment by Athena96** [comment]
Hello all, thank you for your patience. We have deployed a fix for this, so it should no longer be an issue. Feel free to re-open this ticket if you continue to face this or related issues. Thank you!

**Comment by rgevrek** [comment]
Hi,

I have also the issue

`There was an issue connecting to your repo provider, click "Re-authenticate app" in General Settings, and then try your build again.`

in Amplify. I used CodeCommit as git provider.
The APP ARN is arn:aws:amplify:eu-central-1:356761004113:apps/d34faikz7imb88

**Comment by hobyfrezk** [comment]
same here, after try the "Re-authenticate app" button, the issue still here.

**Comment by greenled** [comment]
same issue here

**Comment by SJI-ParthaSarathi** [comment]
Same issue is still there!

**Comment by clovus** [comment]
Same issue! About to give up on Amplify and go back to Netlify. Never had an issue like this.

**Comment by SJI-ParthaSarathi** [comment]
Update:
fixed the issue https://docs.aws.amazon.com/amplify/latest/userguide/how-to-service-role-amplify-console.html
https://github.com/aws-amplify/amplify-console/issues/572

**Comment by oscarnevarezleal** [comment]
The current behavior is extremely buggy. I transferred my repository from my personal account to an organization, when I wanted to do this using the Amplify UI, the _Reconnect repository_ button just kept spinning without allowing me to do any change.


I don't know what exactly did the trick but here's what I tried and end up working allowing me to modify the repository. 

- Remove any manual environment created on the Amplify UI
- Make sure the Oauth Application has been granted access to your repo
- Make sure the Access Token can read repos and also have webhook permissions
- Try to run the update command line, at this point I was getting a diferent error "_An error occurred (BadRequestException) when calling the UpdateApp operation: There was an issue setting up your repository. Please try again later._"
- I came back to the Amplify UI page and a this point I was able to reconfigure the repository again.

**Comment by doyeon326** [comment]
Hi! i got same issue saying after doing it for second times. 
<img width="946" alt="스크린샷 2021-02-22 오후 6 48 35" src="https://user-images.githubusercontent.com/23535790/108691212-99947e80-753e-11eb-81a8-14a87f799eac.png">

I used codeCommit as a gitProvider as well and try to reconnect the app several times but it won't work. I don’t know where i got wrong. Please help me?
<img width="636" alt="스크린샷 2021-02-22 오후 6 50 33" src="https://user-images.githubusercontent.com/23535790/108691445-dd878380-753e-11eb-836e-02b6e666390b.png">

**Comment by ayushjain1594** [comment]
@SJI-ParthaSarathi thanks for sharing that link. 

I hope they add that part in their tutorial at [Build a Full-Stack React Application](https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/)

**Comment by medelman17** [comment]
I, too, have been encountering this issue regularly--although it seems to be a bit of a false flag. Reopening because the UX could be improved.

**Comment by oscarnevarezleal** [comment]
I reproduced the issue. I forgot to specify a Service role ( keeps failing even after ), the error is displayed on the logs

```
!User: arn:aws:sts::073653171576:assumed-role/AemiliaControlPlaneLambda-CodeBuildRole-1PJH7JZRIQRPI/AWSCodeBuild-7cb34b23-8cc1-44d3-8620-bf003e94993c is not authorized to perform: ssm:GetParametersByPath on resource: ***
```

But the UI continues saying:

>There was an issue connecting to your repo provider, click "Re-authenticate app" in General Settings, and then try your build again.

**Comment by pagameba** [comment]
I have the same issue, an error in my amplify.yml file causes the UI to say there is a problem connecting to the repository.

**Comment by JEdureis** [comment]
https://stackoverflow.com/questions/67506585/error-in-aws-amplify-build-when-referencing-private-package-in-aws-codeartifact

**Comment by Jay2113** [comment]
Hi everyone 👋 , over the past several years we have made significant improvements to surface the appropriate build errors in the build logs and we have also added buildSpec validation. This issue has been resolved and should no longer occur.
