### ISSUE TITLE
Monorepo test phase does not run

### ISSUE THREAD

**Issue by lukehedger** [aws-amplify/amplify-console#786]
I have configured a monorepo build, as [described in the docs](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#monorepo-configuration). The `amplify.yml` file looks like this:

```yaml
version: 1
applications:
  - appRoot: app
    frontend:
      artifacts:
        baseDirectory: public
        files:
          - '**/*'
      phases:
        preBuild:
          commands:
            - npm install --no-audit --no-package-lock --no-progress --silent
        build:
          commands:
            - npm run build
    test:
      artifacts:
        baseDirectory: cypress
        files:
          - '**/*.mp4'
          - '**/*.png'
      phases:
        preTest:
          commands:
            - npm install
        test:
          commands:
            - npx cypress run
```

The provision, build, deploy and verify steps all complete successfully. **But the test phase does not appear to run at all and just displays the "Test is still pending or has been canceled for this build." message**.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/1913316/85394114-f8d06800-b545-11ea-802b-dcc7bbad4385.png">

**Comment by abhi7cr** [comment]
Hi @lukehedger.

Thanks for reporting. Can you give your **appid** and **region**?

**Comment by lukehedger** [comment]
Hey @abhi7cr - thanks for your message. Here's the info:

- appid: duqrkr4cxsc1a
- region: eu-west-2

**Comment by abhi7cr** [comment]
Hi @lukehedger,

We have identified the issue, and we are working on a fix. Will let you know once it's rolled out.

**Comment by lukehedger** [comment]
Thanks @abhi7cr 😄

**Comment by FizzBuzz791** [comment]
Hi @abhi7cr - I think I'm experiencing the same bug... with the exception of the mono-repo / app root part of the yaml, they're pretty much the same and I have the same symptoms.

App ID: dldzc7aaj7fba
Region: ap-southeast-2

Are you able to confirm please?

**Comment by abhi7cr** [comment]
Hi @lukehedger @FizzBuzz791,

We have patched a fix for the above, and will let you know once it’s deployed.

**Comment by Athena96** [comment]
Hi @lukehedger @FizzBuzz791 ,
We have deployed the fix for this issue. Please let us know if you are still having trouble, thanks!

**Comment by marianmazarovici** [comment]
@Athena96 I am still experiencing this issue with my monorepo.
Please check in region eu-west-1, ARN `arn:aws:amplify:eu-west-1:823520509658:apps/d6ynoegycmeil`

Contents of amplify.yml:
`
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: dist
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: frontend/

test:
  phases:
    preTest:
      commands:
        - npm install
        - npm ci
        - npm install wait-on
        - npm install mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
        - 'npm run serve & npx wait-on http://localhost:3000'
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
`

**Comment by swaminator** [comment]
Fix has released. Please reopen if you find issues.
